"""empty message

Revision ID: 19cc4d319920
Revises: e2bc11e5680e
Create Date: 2025-03-02 17:34:34.221400

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19cc4d319920"
down_revision: str | None = "e2bc11e5680e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_offers", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_offers", "description")
    # ### end Alembic commands ###
