"""empty message

Revision ID: dedee8ce82ce
Revises: 3f0ef1ef2c5a
Create Date: 2025-03-03 18:42:50.934702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dedee8ce82ce"
down_revision: str | None = "3f0ef1ef2c5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_book_exchanges_id"), "book_exchanges", ["id"])
    op.drop_column("book_exchanges", "exchange_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_exchanges",
        sa.Column(
            "exchange_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(op.f("uq_book_exchanges_id"), "book_exchanges", type_="unique")
    # ### end Alembic commands ###
