"""empty message

Revision ID: e051d91926be
Revises: 19cc4d319920
Create Date: 2025-03-03 10:33:57.286092

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e051d91926be"
down_revision: str | None = "19cc4d319920"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(length=150), nullable=False))
    op.add_column("user", sa.Column("number", sa.String(length=150), nullable=False))
    op.add_column("user", sa.Column("contact", sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "contact")
    op.drop_column("user", "number")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
