"""empty message

Revision ID: e2bc11e5680e
Revises: 126c22095be9
Create Date: 2025-03-02 14:22:35.817168

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2bc11e5680e"
down_revision: str | None = "126c22095be9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_book_main_images_id"), "book_main_images", ["id"]
    )
    op.add_column("book_offers", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_offers", "is_active")
    op.drop_constraint(
        op.f("uq_book_main_images_id"), "book_main_images", type_="unique"
    )
    # ### end Alembic commands ###
