include:
    - local: "/jobs/build.yaml"
    - local: "/jobs/docker.yaml"
    - local: "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

stages:
  - build
  # - lint
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

# lint:
#   stage: lint
#   image: registry.gitlab.com/pipeline-components/ruff:latest
#   script:
#     - ruff check --output-format=gitlab .
#     - ruff format --check --verbose .

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 80:80"

